import streamlit as st
import time

# 1. Page Configuration
st.set_page_config(page_title="GenAI Prompt Studio", page_icon="⚡", layout="centered")

# 2. Main Title & Introduction
st.title("GenAI Prompt Studio")
st.markdown("Welcome to the **GenAI Prompt Studio**! Fill in your prompt below to generate an AI response.")

# 3. Sidebar Configuration
with st.sidebar:
    st.header("Model Configuration")
    temperature = st.slider("Creativity (Temperature)", 0.0, 1.0, 0.7)
    persona = st.radio("AI Persona", ["Medical Assistant", "Code Mentor", "Creative Writer"])

# 4. Session State Initialization
if "last_prompt" not in st.session_state:
    st.session_state.last_prompt = ""
if "last_response" not in st.session_state:
    st.session_state.last_response = ""
if "user_name" not in st.session_state:
    st.session_state.user_name = ""

# 5. Tab Layout
# ❌ BUG 1 FIX NEEDED: st.tabs() expects a LIST of tab names, e.g. ["Tab 1", "Tab 2"]!
tab_form, tab_output = st.tabs(["Prompt Form", "Output Result"])

# Tab 1: Input Form
with tab_form:
    st.subheader("Submit Your Prompt")
    
    with st.form(key="genai_form"):
        user_name = st.text_input("Your Name *", placeholder="e.g., Alex")
        prompt_text = st.text_area("Prompt Instructions *", placeholder="e.g., Explain Python functions in simple terms.")
        
        # ❌ BUG 2 FIX NEEDED: Inside a form, you MUST use st.form_submit_button() instead of st.button()!
        submit_button = st.form_submit_button("Generate Response")

    if submit_button:
        st.error(
                "Please enter both your name and prompt instructions."
            ) # TODO 1: Check if user_name or prompt_text is empty (strip whitespace), and show st.error() if empty.
        
        # TODO 2: Complete the simulation progress loop below so the progress bar advances from 1 to 100.
        st.info("AI is crafting your response...")
        progress_bar = st.progress(0)
        for i in range(100):
            time.sleep(0.01)
            progress_bar.progress(i + 1) # Fill in progress bar step here! (e.g. progress_bar.progress(i + 1))
            pass

        # TODO 3: Save user_name, persona, temperature, and prompt_text into st.session_state.last_response
        st.session_state.user_name = user_name
        st.session_state.last_prompt = prompt_text

        st.session_state.last_response = f"""
### AI Response

**Hello {user_name}! 👋**

**Selected Persona:** {persona}  
**Creativity (Temperature):** {temperature} here is a response to your prompt: 

{prompt_text}

---

Here is a response generated by the
**{persona}** persona with a creativity level of **{temperature}**.
""" # st.session_state.last_response = ...

        st.balloons()
        st.success("Response generated! Switch to the **Output Result** tab to view it.")

# Tab 2: Output Display
with tab_output:
    st.subheader("Generated AI Output")
    # TODO 4: Check if st.session_state.last_response has content. 
    # If yes, display it using st.markdown(). If no, show st.info("No response generated yet...")
    if st.session_state.last_response:
        st.markdown(st.session_state.last_response)
    else:
        st.info("No response generated yet...")
